### ISSUE TITLE
getLinks fails

### ISSUE THREAD

**Issue by travisghansen** [mildsunrise/node_netlink#16]
```
Error: Not null terminated
    at Object.getString (/home/thansen/Projects/github/travisghansen/metallb-node-route-agent/node_modules/netlink/dist/structs.js:312:15)
    at Object.54 (/home/thansen/Projects/github/travisghansen/metallb-node-route-agent/node_modules/netlink/dist/rt/ifla.js:245:52)
```

**Comment by mildsunrise** [comment]
the wonders of netlink and poor documentation!
it seems strings don't necessarily have to be nul terminated, let me check how libnl handles this...

**Comment by mildsunrise** [comment]
ah no, strings are alright, it's just that the enum wasn't parsed correctly and some attribute IDs were shifted by one

**Comment by travisghansen** [comment]
I've wiped out the module and reinstalled but seem to still be getting this error..I'm not sure exactly where I can look to be sure I've got the updated code however.

**Comment by mildsunrise** [comment]
you need to rerun the code generation, sorry. I do it before every release, but didn't do it yet since I want to look at #14 first (which is probably a similar issue to this one)

**Comment by travisghansen** [comment]
Ok I’ll try that out..
