### ISSUE TITLE
help me to use node_netlink to set and get wireguard config

### ISSUE THREAD

**Issue by Sirherobrine23** [mildsunrise/node_netlink#18]
hi, I'm starting a module to manage Wireguard interfaces through node, I never got close to netlink and even close to interacting with the kernel, I'm relying entirely on [wireguard-tools](https://github.com/WireGuard/wireguard-tools/tree/master/src), [wgctrl-go](https://github.com/WireGuard/wgctrl-go) and [pyroute2](https://github.com/svinota/pyroute2/blob/master/pyroute2/netlink/generic/wireguard.py).

I'm modifying the `wireguard-tools` in the netlink part to know how it interacts, I'm using an [pull request](https://github.com/Sirherobrine23/Wireguard-tools.js/pull/3) in my repository to store what I get,
I was wondering if anyone could help me with the netlink part.

**Comment by mildsunrise** [comment]
hi! I'm currently not up for that, but if you have specific questions or issues that's welcome :)

**Comment by Sirherobrine23** [comment]
ok thanks, but I have one, I'm using the generic request to filter the families but I'm a little confused, I need to get the interfaces but I'm not able to filter the interfaces. when using the Wireguard family, in the request, I create [function](https://github.com/Sirherobrine23/Wireguard-tools.js/blob/aaa2ef034cb2466cf9a18977c649e5ee2130edc6/src/netlink/index.ts#L49) to filter, so not works.

**Comment by mildsunrise** [comment]
I can't make any sense of the message you hardcoded there.
Since it's a relatively small API, I'll add types for it...

**Comment by Sirherobrine23** [comment]
I'm going to test some things, I will still be testing.

**Comment by Sirherobrine23** [comment]
Being able to filter wireguard's network interfaces by `getLinks() -> attrs -> linkinfo -> toString()` (here it says it's a `wireguard` interface), [the function is here](https://github.com/Sirherobrine23/Wireguard-tools.js/blob/4801bb6454b817af0289f369bd69169f39d83dd2/src/netlink/index.ts#L53). Now I'm going to see how to create a Wireguard interface without having to run `ip link add dev {INTERFACE NAME} type wireguard`.

I'm much more optimistic now that I can get the interfaces, I created a TODO in the pull request, I still have a lot to do.

**Comment by mildsunrise** [comment]
the contents of linkinfo are [currently set](https://dolby.tap.thinksmart.com/prod/Portal/WorkflowDashboard) as `data`, which likely indicates that the types for its contents are missing. if you want to help make node-netlink better, you can investigate what it's supposed to hold and create types for it. This is also what I'm going to do for the wireguard API.

**Comment by mildsunrise** [comment]
took me longer than expected but I've mapped the types and API, see https://github.com/mildsunrise/node_netlink/commit/59dbc1edb72ad54c951d5a3123b56616b20d4875.

I probably won't release it until it gets some testing, though

**Comment by Sirherobrine23** [comment]
ok, I'll take a look later, I'm using the `embeddable-wg-library` module to implement Wireguard.
