### ISSUE TITLE
Incorrect length checking in formatAttribute 

### ISSUE THREAD

**Issue by dhl** [mildsunrise/node_netlink#2]
Hi @mildsunrise! Thanks for making this awesome library.

I tried using `formatAttribute`, but was not able to make it work because the length check seems to have been flipped:

https://github.com/mildsunrise/node_netlink/blob/48099d7f28c779d76f94bc0b58a98ff758ea700e/lib/structs.ts#L274-L279

Would you mind taking a look? Thanks again!

**Comment by mildsunrise** [comment]
wow, thanks for the heads up!! I didn't notice because I was using the `AttrStream` API :sweat_smile:

**Comment by mildsunrise** [comment]
0.1.4 is up :)
